name: Sync Upstream

permissions:
  contents: write  # 允许写入代码
on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史，以便能够合并

      - name: Set upstream remote
        run: |
          git remote add upstream https://github.com/xiaojieonly/Ehviewer_CN_SXJ.git
          git fetch upstream
          git config --global user.email "haostart@hotmail.com"
          git config --global user.name "haostart"

      - name: Merge upstream changes
        run: |
          git checkout dev
          git merge upstream/BiLi_PC_Gamer --no-commit --no-ff
        continue-on-error: false  # 如果合并失败，Action会停止执行

      - name: Check if there are changes
        id: check_changes
        run: |
          CHANGES=$(git status --porcelain)
          if [ -n "$CHANGES" ]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit and push if there are changes
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git commit -am "Sync with upstream BiLi_PC_Gamer"
          git push https://${{ secrets.GH_TOKEN }}@github.com/haostart/Ehviewer_CN_SXJ.git dev

      - name: Notify on failure
        if: failure()
        run: echo "Merge failed, please check the logs and resolve conflicts."